name: Build source to server
on:
  push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build source files
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf build.tar ../build/

    - name: Send built files via SCP (SSH connection)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "build.tar"
        target: "."

    - name: SSH into server and finish building (serverside)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: bash build.sh