name: Deploy bot on server
on:
  workflow_dispatch:
  schedule:
    # Re-deploy every 12 hours on the 30th minute
    - cron: "30 */12 * * *"
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    - name: SSH into server and run deployment (Serverside)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: bash deploy.sh