name: Deploy to server
on:
  push
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build source files
      run: |
        mkdir ../build
        cp -TR . ../build

    - name: Deploy via SCP (SSH connection)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "../build"
        target: "src"
